### ISSUE TITLE
Możemy zrobić komendę na sprawdzanie.

### ISSUE THREAD

**Issue by elopider** [blaze-mc-pl/bCorePvP#5]
Komenda na sprawdzanie przydaje się, gdy na przykład nie mamy pewności, że gracz posiada niedozwolone modyfikacje i/lub posiada blazingpack/cmpack itd., a pomimo to zachowuje się podejrzanie.

**Comment by PolskiStevek** [comment]
tak

**Comment by elopider** [comment]
Polecasz mój pomysł? Tylko ja tego nie napisze XD. Nieno to nie byłoby (chyba) takie trudne.

**Comment by PolskiStevek** [comment]
zrobisz komendy a ja dorobie managera i blokowanie komend.

**Comment by elopider** [comment]
Ja coś zepsuje ale okej

**Comment by PolskiStevek** [comment]
pewnie tak

**Comment by elopider** [comment]
Wyśle ci mój kod na komende /op to mnie wyśmiejesz

**Comment by Nikodemeq** [comment]
to wyslij

**Comment by elopider** [comment]
Nikodemeq_ Ty i tak nie zrozumiesz jak on działa. Więc nie opłaca się.

**Comment by PolskiStevek** [comment]
Został dodany nowy antycheat więc prawdopodobnie nie będzie potrzeby sprawdzania cheaterów
